---
title: "EAEPAAE/P: Our take on EPA for punters"
description: |
  A statistical journey to EPA/punt
author:
  - name: Dennis Brookner
    affiliation: Puntalytics
    affiliation_url: https://twitter.com/ThePuntRunts
  - name: Raphael Laden-Guindon
    affiliation: Puntalytics
    affiliation_url: https://twitter.com/ThePuntRunts
date: 08-19-2020
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction
The punchline of this article is a metric, Era-adjusted EPA Above Expectation / Punt (EAEPAAE/P, for short). No, we're not thrilled with that acronym, and yes, it's crazy that every relevant word starts with an E, P, or A. Below, we'll describe the problem(s) with using traditional EPA for punting, and walk through our stab at fixing that.
### The trouble(s) with EPA for punting
First off, if you aren't familiar with EPA, please tweet at [Ben Baldwin](https://twitter.com/benbbaldwin) saying "hey I hear you should always draft a RB in the first round." That should successfully summon him and get you all the information you need.  
  
EPA is essentially too smart for proper puntalytics; it knows more than it should. Specifically, EPA knows all the details of the game script (score, time remaining, yards to go) which influence whether or not you should be punting, and thus also influence how valuable a punt can be. EPA also knows the outcome of the play; was it just a usual <5 yard return, or did it result in a touchdown for one team or the other? Fluke TD outcomes will dominate our averages. Adjusting for these two factors, along with era-adjustment, make up most of the work ahead of us.
## RERUN: Return-Edited Real Unbiased Net
Now this is an acronym we're proud of. We previously developed RERUN in order to account for extreme results; read about it in [this twitter thread](https://twitter.com/ThePuntRunts/status/1235374680313233408?s=20). In brief, RERUN makes two key assumptions:  
  
1. The punter is 100 % responsible for whether or not a punt is returned (vs. being downed, out-of-bounds, fair caught, or a touchback)  
2. The punter is 0 % responsible for the length of any return that does happen.  
  
The result is a stat that is very similar to the usual Net Yards / Punt, but doesn't contain any fluke results, and also adds some subtle corrections for the quality of a punter's coverage team.  
# Fun with EPA

